a=int(input('Enter a number: '))
b=int(input('Enter a number: '))
print("Add",a+b)
print('Sub',a-b)
print('Multi',a*b)
print('Division',a/b)
print('FloorDiv',a//b)
print('modulodiv',a%b)
print('exponent',a**b)
print(a and b)
print(a or b)
print(a&b)
print(a|b)
print(a<b)
print(a>b)
print(~a)
print(a>>b)
print(a<<b)
print(a is b)
print(a is not b)
print("A") if a>b else print("B")



